name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          version:  16.x
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Build
        user: retypeapp/action-build@latest

      - name: Deploy
        uses: retypeapp/action-github-pages@latest
        with:
          branch: gh-pages
          update-branch: true

    
