name: Build React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          version:  16.x
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Build
        uses: rnpm install && npm run build

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy build files
        run: |
          cp -r build/* gh-pages
          cd gh-pages
          git config --local user.email "githubaction@email.com" 
          git config --local user.name "githubaction"
          
      - name: Commit and push changes
        run: |
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push  origin gh-pages


     
       

    
