name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          version:  16.x
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Build and deploy
        run:  npm run deploy

    
